server:
  port: 8995

spring:

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: lemon
    lettuce:
      pool:
        max-active: 200
        max-idle: 11
        max-wait: -1ms
        min-idle: 0
    timeout: 6000ms