server:
  port: 8994

spring:
  # datasource
  datasource:
    url: jdbc:mysql:///oauth2-code-auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: cms
    password: wdit@123
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: hikariCP

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: lemon
    lettuce:
      pool:
        max-active: 200
        max-idle: 11
        max-wait: -1ms
        min-idle: 0
    timeout: 6000ms